export const DEFAULT_CONFIG = {
  providers: [
    { id: 'kimi', name: 'Kimi', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
    { id: 'deepseek', name: 'DeepSeek', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
    { id: 'openai', name: 'OpenAI', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
    { id: 'groq', name: 'Groq', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
    { id: 'gemini', name: 'Gemini', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
    { id: 'anthropic', name: 'Anthropic', status: 'idle', apiKey: '', lastValidated: '-', disabled: false },
  ],
  commands: [
    { id: '1', name: '/start', category: 'General', status: 'active', response: 'Hello! I am FanraBot. How can I assist you?' },
    { id: '2', name: '/help', category: 'General', status: 'active', response: 'Here is the list of available commands...\n\n/start - Start the bot\n/help - Show this help message\n/harga - View the product price list\n/promo - Get special promo code\n/ping - Test bot response speed' },
    { id: '3', name: '/harga', category: 'Business', status: 'active', response: 'Our product price list is as follows:\n- Standard Package: Rp 50.000 / bln\n- Premium Package: Rp 150.000 / bln\n- Business Package: Rp 350.000 / bln' },
    { id: '4', name: '/stok', category: 'Business', status: 'inactive', response: 'Sorry, stock checking is currently under maintenance.' },
    { id: '5', name: '/promo', category: 'Business', status: 'active', response: 'Use code FANRA10 for a 10% discount!' },
    { id: '6', name: '/ping', category: 'Utility', status: 'active', response: 'Pong! The bot is active and ready to serve.' },
  ],
  settings: {
    botName: "FanraBot Assistant",
    languageStyle: "Casual & Friendly",
    persona: "A human-like smart and friendly personal assistant",
    systemPrompt: `You are FanraBot, a fun, friendly, and smart AI assistant created by Kak Fanra.\n\nCore Rules:\n1. Speak warmly and interactively like a real human. Avoid overly robotic, formal, or sales-like tones.\n2. Do NOT act like a generic AI assistant. If you don't know something, ask clarifying questions casually (e.g. "what do you mean by that?", "I'm not exactly sure") instead of referring them to customer support immediately.\n3. Keep your replies concise and straight to the point.`,
    autoReply: true,
    autoReplyEnabled: true,
    groupReply: false,
    privateReply: true,
    blockedNumbers: "",
    aiMemory: true,
    typingEffect: true,
    ownerNumber: "628123456789",
    excludeKeywords: "promo, diskon, stop",
    commandPrefix: "/",
    botTemperament: "ramah",
    defaultLanguage: "en",
    welcomeEnabled: true,
    welcomeMode: "image",
    welcomeCardTheme: "cosmic_neon",
    welcomeCardQuote: "Semoga harimu menyenangkan dan mari berkembang bersama!",
    welcomeNewContactsOnly: false,
    welcomeDelaySeconds: 0,
    welcomeMessage: "Welcome @user to @group! Glad to have you here. Enjoy your stay! 😊",
    antiLinkEnabled: true,
    antiLinkBlockAdmin: false,
    antiLinkFilterScope: "except_admin",
    antiLinkAction: "delete",
    antiLinkAlert: "⚠️ Group rules violation! Links are not allowed.",
    antiSpamEnabled: true,
    spamAction: "delete",
    antiSpamAlert: "⚠️ Please do not spam! You have been warned.",
    antiTagAllEnabled: false,
    antiTagAllThreshold: 5,
    antiTagAllAllowed: "admin_only",
    antiTagAllAlert: "⚠️ Mass mentioning is not allowed!",
    autoStickerEnabled: true,
    keywordResponseEnabled: true,
    downloaderEnabled: true,
    stickerToolsEnabled: true,
    stickerToImageEnabled: true,
    qrToolsEnabled: true,
    qrGeneratorEnabled: true,
    qrReaderEnabled: true,
    adminToolsAlert: "Sorry, this command can only be executed by Group Admins!",
    broadcastMessage: "Hello! Thank you for choosing FanraBot. Contact us if you need anything.",
    antiCallMessage: "Hello! Unfortunately, we cannot accept calls at the moment. Please send us a text message.",
    antiVirtexLength: 8000,
    antiRaidAction: "demote",
    toUrlEnabled: true,
    playMp3Enabled: true,
    compressMediaEnabled: true,
    removeBgEnabled: true,
    removeBackgroundEnabled: true,
    broadcastEnabled: false,
    broadcastTime: "12:00",
    aggressiveAI: false,
    aggressiveAiMode: false,
    aggressiveAITarget: "group",
    aggressiveAIMinMessages: 3,
    aggressiveAIProbability: 15,
    aggressiveAILanguage: "auto",
    antiBadwordEnabled: true,
    badWords: "anjing, babi, bangsat, keparat, bajingan, kontol, memek, asu, dancok, peler, patek, tolol, goblok, bangsadd, ngentot, ngewe, tetek, perek, lonte, jembut, kntl, ajg, bgst, gblk, bego, fuck, shit, bitch, asshole, dick, pussy, bastard, cunt, motherfucker, wanker, slut, whore, crap",
    errorDelayMinutes: 5,
    hdImageEnabled: true,
    hdUpscalerEnabled: true,
    photoRestoreEnabled: true,
    musicRecognitionEnabled: true,
    pdfToolsEnabled: true,
    translateEnabled: true,
    translateManualEnabled: true,
    fileInspectorEnabled: true,
    shortUrlEnabled: true,
    
    openGroupEnabled: true,
    closeGroupEnabled: true,
    linkGroupEnabled: true,
    revokeGroupLinkEnabled: true,
    promoteEnabled: true,
    demoteEnabled: true,
    kickEnabled: true,
    deleteMessageEnabled: true,

    antiRaidEnabled: false,
    antiRaidMode: "admin_only",
    antiRaidNotify: true,

    pinnedAutomationFeatures: [],

    shortUrlProvider: "TinyURL",
    shortUrlCustomAlias: "",
    shortUrlDomain: "",
    shortUrlAutoCopy: true,

    autoTranslateEnabled: false,
    autoTranslateTargetLang: "en",
    autoTranslateMode: "foreign_only",
    autoTranslateScope: "all",
    autoTranslateShowOriginal: false,
    naturalLanguageToolsEnabled: true,
    naturalLanguageWakeWord: "fanra",
    privateNaturalIntentEnabled: true,
    aiIntentFallbackEnabled: false
  },
  menuPreview: {
    bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    sourceUrl: "https://ais-pre-gwuyfiowtcdy7aefbcel6w-104687641554.asia-southeast1.run.app",
    title: "FanraBot Menu",
    description: "Smart WhatsApp Assistant"
  }
};
